//! Rust-Native Exit Evaluator — Institutional Upgrade.
//!
//! Moves ALL exit logic (Parabolic SAR, ATR Trailing Stop, Chandelier Exit)
//! from the Python polling path into the Rust hot path. Exits are now evaluated
//! on EVERY tick from the live WebSocket stream, eliminating the 10-50ms Python
//! REST polling latency.
//!
//! # Integration
//!
//! Called from `tick_processor.rs` or `strategy_evaluator_loop` on every
//! BookSnapshot, immediately after the strategy evaluator runs. If an exit
//! is triggered, an OrderCommand with `order_type = MARKET` and `side = opposite`
//! is pushed directly into the execution SPSC ring.
//!
//! # Supported Exit Strategies
//!
//! 1. **Parabolic SAR** — Welles Wilder's classic trend-following stop.
//!    Accelerates toward price, triggers when SAR crosses price.
//!
//! 2. **ATR Trailing Stop** — Trails at N × ATR behind the extremum.
//!    Adapts to volatility automatically.
//!
//! 3. **Chandelier Exit** — Highest high (or lowest low) minus N × ATR.
//!    Designed for trending markets.
//!
//! 4. **Hard SL/TP** — Immediate trigger if price crosses the stop_loss
//!    or take_profit levels set on the OrderCommand.
//!
//! # Thread Safety
//!
//! `ExitEvaluator` is NOT thread-safe — it is owned by a single thread
//! (the strategy evaluator on Core 4). No locking needed.

use std::collections::HashMap;
use tracing::info;

// ═══════════════════════════════════════════════════════════════════════════
// Exit Signal
// ═══════════════════════════════════════════════════════════════════════════

/// An exit signal generated by the evaluator.
#[derive(Debug, Clone, Copy)]
pub struct ExitSignal {
    /// Symbol ID of the position to close.
    pub symbol_id: u16,
    /// Side of the EXIT order (opposite of position). 0 = buy, 1 = sell.
    pub exit_side: u8,
    /// Reason for exit.
    pub reason: ExitReason,
    /// Urgency: 0 = normal, 1 = high, 2 = emergency.
    pub urgency: u8,
    /// Suggested exit price (0 = market order).
    pub suggested_price_fp: i64,
}

/// Why an exit was triggered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExitReason {
    /// Parabolic SAR crossed price.
    ParabolicSarCross,
    /// ATR trailing stop hit.
    AtrTrailingStop,
    /// Chandelier exit triggered.
    ChandelierExit,
    /// Hard stop loss price breached.
    HardStopLoss,
    /// Take profit price reached.
    TakeProfit,
    /// Time-based expiry (TTL exceeded).
    TimeExpiry,
    /// Upgrade 4: Trailing stop moved to break-even.
    TrailingBreakEven,
    /// Upgrade 4: Trailing stop (ATR-based) was hit.
    TrailingAtrStop,
    /// Upgrade 4: Partial take-profit at R:R level.
    PartialTakeProfit,
}

impl std::fmt::Display for ExitReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ExitReason::ParabolicSarCross => write!(f, "psar_cross"),
            ExitReason::AtrTrailingStop => write!(f, "atr_trail"),
            ExitReason::ChandelierExit => write!(f, "chandelier"),
            ExitReason::HardStopLoss => write!(f, "hard_sl"),
            ExitReason::TakeProfit => write!(f, "hard_tp"),
            ExitReason::TimeExpiry => write!(f, "time_expiry"),
            ExitReason::TrailingBreakEven => write!(f, "trailing_be"),
            ExitReason::TrailingAtrStop => write!(f, "trailing_atr"),
            ExitReason::PartialTakeProfit => write!(f, "partial_tp"),
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Parabolic SAR State
// ═══════════════════════════════════════════════════════════════════════════

/// Per-position Parabolic SAR state machine.
///
/// Implements Welles Wilder's Parabolic SAR with:
/// - Initial acceleration factor (AF) of 0.02
/// - AF increment of 0.02 per new extreme
/// - Maximum AF of 0.20
#[derive(Debug, Clone)]
struct ParabolicSarState {
    /// Current SAR value.
    sar: f64,
    /// Extreme point (highest high for longs, lowest low for shorts).
    extreme_point: f64,
    /// Current acceleration factor.
    af: f64,
    /// Whether this is tracking a long position.
    is_long: bool,
    /// Number of updates received.
    tick_count: u32,
}

impl ParabolicSarState {
    const AF_INITIAL: f64 = 0.02;
    const AF_INCREMENT: f64 = 0.02;
    const AF_MAX: f64 = 0.20;

    fn new(entry_price: f64, is_long: bool) -> Self {
        Self {
            sar: entry_price,
            extreme_point: entry_price,
            af: Self::AF_INITIAL,
            is_long,
            tick_count: 0,
        }
    }

    /// Update SAR with a new high/low tick.
    /// Returns `true` if the SAR was crossed (exit signal).
    fn update(&mut self, high: f64, low: f64) -> bool {
        self.tick_count += 1;

        // Need at least 2 ticks before generating signals
        if self.tick_count < 2 {
            if self.is_long {
                self.extreme_point = self.extreme_point.max(high);
            } else {
                self.extreme_point = self.extreme_point.min(low);
            }
            return false;
        }

        if self.is_long {
            // Long position: SAR is below price
            // Check if SAR was crossed (price fell below SAR)
            if low <= self.sar {
                return true; // Exit signal
            }

            // Update extreme point
            if high > self.extreme_point {
                self.extreme_point = high;
                self.af = (self.af + Self::AF_INCREMENT).min(Self::AF_MAX);
            }

            // Advance SAR
            self.sar = self.sar + self.af * (self.extreme_point - self.sar);

            // SAR must not be above the prior two lows (clamping)
            self.sar = self.sar.min(low);
        } else {
            // Short position: SAR is above price
            if high >= self.sar {
                return true; // Exit signal
            }

            if low < self.extreme_point {
                self.extreme_point = low;
                self.af = (self.af + Self::AF_INCREMENT).min(Self::AF_MAX);
            }

            self.sar = self.sar - self.af * (self.sar - self.extreme_point);
            self.sar = self.sar.max(high);
        }

        false
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// ATR Calculator
// ═══════════════════════════════════════════════════════════════════════════

/// Incremental ATR calculator using Wilder's smoothing (EMA with period N).
#[derive(Debug, Clone)]
struct AtrCalculator {
    /// Current ATR value.
    atr: f64,
    /// ATR period (number of bars).
    period: usize,
    /// Previous close for TR calculation.
    prev_close: f64,
    /// Number of samples received.
    sample_count: usize,
    /// Sum of initial TRs for warm-up.
    warmup_sum: f64,
}

impl AtrCalculator {
    fn new(period: usize) -> Self {
        Self {
            atr: 0.0,
            period,
            prev_close: 0.0,
            sample_count: 0,
            warmup_sum: 0.0,
        }
    }

    /// Update ATR with a new OHLC bar.
    /// Returns the current ATR value.
    fn update(&mut self, high: f64, low: f64, close: f64) -> f64 {
        if self.sample_count == 0 {
            self.prev_close = close;
            self.sample_count = 1;
            self.atr = high - low; // First bar: TR = high - low
            self.warmup_sum = self.atr;
            return self.atr;
        }

        // True Range = max(high - low, |high - prev_close|, |low - prev_close|)
        let tr = (high - low)
            .max((high - self.prev_close).abs())
            .max((low - self.prev_close).abs());

        self.sample_count += 1;

        if self.sample_count <= self.period {
            // Warm-up: simple average
            self.warmup_sum += tr;
            self.atr = self.warmup_sum / self.sample_count as f64;
        } else {
            // Wilder's smoothing: ATR = ((ATR * (N-1)) + TR) / N
            self.atr = ((self.atr * (self.period as f64 - 1.0)) + tr) / self.period as f64;
        }

        self.prev_close = close;
        self.atr
    }

    /// Get current ATR (returns 0 if not enough data).
    fn get(&self) -> f64 {
        self.atr
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Per-Position Exit State
// ═══════════════════════════════════════════════════════════════════════════

/// Complete exit tracking state for a single position.
#[derive(Debug, Clone)]
struct PositionExitState {
    /// Symbol ID.
    symbol_id: u16,
    /// Position side: true = long, false = short.
    is_long: bool,
    /// Entry price.
    entry_price: f64,
    /// Hard stop loss price (0 = none).
    stop_loss: f64,
    /// Hard take profit price (0 = none).
    take_profit: f64,
    /// Position size in contracts.
    size: i64,
    /// Timestamp when position was opened (nanoseconds).
    opened_ns: u64,
    /// Maximum TTL in nanoseconds (0 = no expiry).
    ttl_ns: u64,

    /// Parabolic SAR state.
    psar: ParabolicSarState,
    /// ATR calculator (14-period).
    atr: AtrCalculator,
    /// ATR trailing stop multiplier.
    atr_multiplier: f64,
    /// Highest high since entry (for longs) / lowest low (for shorts).
    extremum: f64,
    /// Current trailing stop level.
    trailing_stop: f64,
    /// Chandelier exit multiplier.
    chandelier_multiplier: f64,
}

impl PositionExitState {
    fn new(
        symbol_id: u16,
        is_long: bool,
        entry_price: f64,
        stop_loss: f64,
        take_profit: f64,
        size: i64,
        ttl_ns: u64,
    ) -> Self {
        Self {
            symbol_id,
            is_long,
            entry_price,
            stop_loss,
            take_profit,
            size,
            opened_ns: now_ns(),
            ttl_ns,
            psar: ParabolicSarState::new(entry_price, is_long),
            atr: AtrCalculator::new(14),
            atr_multiplier: 3.0,
            extremum: entry_price,
            trailing_stop: if is_long {
                entry_price * 0.97 // Initial 3% trailing for longs
            } else {
                entry_price * 1.03 // Initial 3% trailing for shorts
            },
            chandelier_multiplier: 3.0,
        }
    }

    /// Evaluate all exit conditions against the current tick.
    /// Returns `Some(ExitSignal)` if any exit condition is met.
    fn evaluate(
        &mut self,
        high: f64,
        low: f64,
        close: f64,
        mid_price: f64,
    ) -> Option<ExitSignal> {
        let exit_side = if self.is_long { 1u8 } else { 0u8 }; // opposite side

        // 1. Hard Stop Loss check (highest priority)
        if self.stop_loss > 0.0 {
            if self.is_long && mid_price <= self.stop_loss {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::HardStopLoss,
                    urgency: 2, // emergency
                    suggested_price_fp: 0, // market order
                });
            }
            if !self.is_long && mid_price >= self.stop_loss {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::HardStopLoss,
                    urgency: 2,
                    suggested_price_fp: 0,
                });
            }
        }

        // 2. Take Profit check
        if self.take_profit > 0.0 {
            if self.is_long && mid_price >= self.take_profit {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::TakeProfit,
                    urgency: 1,
                    suggested_price_fp: 0,
                });
            }
            if !self.is_long && mid_price <= self.take_profit {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::TakeProfit,
                    urgency: 1,
                    suggested_price_fp: 0,
                });
            }
        }

        // 3. Time-based expiry
        if self.ttl_ns > 0 {
            let elapsed = now_ns().saturating_sub(self.opened_ns);
            if elapsed > self.ttl_ns {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::TimeExpiry,
                    urgency: 1,
                    suggested_price_fp: 0,
                });
            }
        }

        // 4. Update ATR
        let atr = self.atr.update(high, low, close);

        // 5. Update extremum and ATR trailing stop
        if self.is_long {
            if high > self.extremum {
                self.extremum = high;
            }
            if atr > 0.0 {
                let new_trail = self.extremum - self.atr_multiplier * atr;
                // Trailing stop only moves up for longs
                self.trailing_stop = self.trailing_stop.max(new_trail);
            }
            if mid_price <= self.trailing_stop {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::AtrTrailingStop,
                    urgency: 1,
                    suggested_price_fp: 0,
                });
            }
        } else {
            if low < self.extremum {
                self.extremum = low;
            }
            if atr > 0.0 {
                let new_trail = self.extremum + self.atr_multiplier * atr;
                // Trailing stop only moves down for shorts
                self.trailing_stop = self.trailing_stop.min(new_trail);
            }
            if mid_price >= self.trailing_stop {
                return Some(ExitSignal {
                    symbol_id: self.symbol_id,
                    exit_side,
                    reason: ExitReason::AtrTrailingStop,
                    urgency: 1,
                    suggested_price_fp: 0,
                });
            }
        }

        // 6. Chandelier Exit
        if atr > 0.0 {
            if self.is_long {
                let chandelier = self.extremum - self.chandelier_multiplier * atr;
                if mid_price <= chandelier {
                    return Some(ExitSignal {
                        symbol_id: self.symbol_id,
                        exit_side,
                        reason: ExitReason::ChandelierExit,
                        urgency: 1,
                        suggested_price_fp: 0,
                    });
                }
            } else {
                let chandelier = self.extremum + self.chandelier_multiplier * atr;
                if mid_price >= chandelier {
                    return Some(ExitSignal {
                        symbol_id: self.symbol_id,
                        exit_side,
                        reason: ExitReason::ChandelierExit,
                        urgency: 1,
                        suggested_price_fp: 0,
                    });
                }
            }
        }

        // 7. Parabolic SAR
        if self.psar.update(high, low) {
            return Some(ExitSignal {
                symbol_id: self.symbol_id,
                exit_side,
                reason: ExitReason::ParabolicSarCross,
                urgency: 1,
                suggested_price_fp: 0,
            });
        }

        None
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// ExitEvaluator — manages all position exits
// ═══════════════════════════════════════════════════════════════════════════

/// Manages exit evaluation for all active positions.
///
/// Owned by the strategy evaluator thread. NOT thread-safe.
pub struct ExitEvaluator {
    /// Active position exit states, keyed by a composite key (symbol_id).
    positions: HashMap<u16, PositionExitState>,
    /// Total exits triggered.
    pub total_exits: u64,
    /// Exits by reason.
    pub exits_by_reason: HashMap<String, u64>,
}

impl ExitEvaluator {
    pub fn new() -> Self {
        Self {
            positions: HashMap::with_capacity(16),
            total_exits: 0,
            exits_by_reason: HashMap::new(),
        }
    }

    /// Register a new position for exit tracking.
    pub fn track_position(
        &mut self,
        symbol_id: u16,
        is_long: bool,
        entry_price: f64,
        stop_loss: f64,
        take_profit: f64,
        size: i64,
        ttl_ns: u64,
    ) {
        let state = PositionExitState::new(
            symbol_id, is_long, entry_price, stop_loss, take_profit, size, ttl_ns,
        );
        self.positions.insert(symbol_id, state);
        info!(
            "[exit-eval] Tracking {} position for sym {} @ {:.4} SL={:.4} TP={:.4}",
            if is_long { "LONG" } else { "SHORT" },
            symbol_id, entry_price, stop_loss, take_profit
        );
    }

    /// Remove a position from exit tracking (after exit order is submitted).
    pub fn untrack_position(&mut self, symbol_id: u16) {
        self.positions.remove(&symbol_id);
    }

    /// Evaluate all tracked positions against the current market data.
    /// Returns a list of exit signals for positions that should be closed.
    ///
    /// `high`, `low`, `close` are synthetic from the book snapshot:
    /// - high = best_ask (worst case for longs)
    /// - low  = best_bid (worst case for shorts)
    /// - close = mid_price
    pub fn evaluate_all(
        &mut self,
        symbol_id: u16,
        high: f64,
        low: f64,
        close: f64,
        mid_price: f64,
    ) -> Vec<ExitSignal> {
        let mut signals = Vec::new();

        if let Some(state) = self.positions.get_mut(&symbol_id) {
            if let Some(signal) = state.evaluate(high, low, close, mid_price) {
                info!(
                    "[exit-eval] 🚨 EXIT triggered for sym {}: reason={}, urgency={}",
                    symbol_id, signal.reason, signal.urgency
                );
                self.total_exits += 1;
                *self.exits_by_reason
                    .entry(signal.reason.to_string())
                    .or_insert(0) += 1;
                signals.push(signal);
            }
        }

        signals
    }

    /// Check if a position is being tracked for a symbol.
    pub fn is_tracking(&self, symbol_id: u16) -> bool {
        self.positions.contains_key(&symbol_id)
    }

    /// CHECK #4: Block duplicate positions per symbol.
    /// Returns true if the symbol already has an open position being tracked.
    pub fn has_position(&self, symbol_id: u16) -> bool {
        self.positions.contains_key(&symbol_id)
    }

    /// Get the number of positions being tracked.
    pub fn tracked_count(&self) -> usize {
        self.positions.len()
    }

    /// Update the SL/TP for a tracked position (dynamic adjustment).
    pub fn update_sl_tp(&mut self, symbol_id: u16, new_sl: f64, new_tp: f64) {
        if let Some(state) = self.positions.get_mut(&symbol_id) {
            if new_sl > 0.0 {
                state.stop_loss = new_sl;
            }
            if new_tp > 0.0 {
                state.take_profit = new_tp;
            }
        }
    }

    /// Detect unprotected positions (no SL and/or no TP set).
    ///
    /// Returns a list of (symbol_id, is_long, entry_price, has_sl, has_tp) for
    /// positions that are missing SL or TP protection. The caller is responsible
    /// for computing and applying appropriate SL/TP values (e.g. ATR-based).
    pub fn get_unprotected_positions(&self) -> Vec<(u16, bool, f64, bool, bool)> {
        let mut unprotected = Vec::new();
        for (_, state) in &self.positions {
            let has_sl = state.stop_loss > 0.0;
            let has_tp = state.take_profit > 0.0;
            if !has_sl || !has_tp {
                unprotected.push((
                    state.symbol_id,
                    state.is_long,
                    state.entry_price,
                    has_sl,
                    has_tp,
                ));
            }
        }
        unprotected
    }
}

impl Default for ExitEvaluator {
    fn default() -> Self {
        Self::new()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Upgrade 4: Trailing Stop-Loss with Break-Even Move
// ═══════════════════════════════════════════════════════════════════════════

/// Action requested by the trailing stop update logic.
#[derive(Debug, Clone)]
pub enum TrailingStopUpdate {
    /// Move SL to break-even (entry price).
    MoveToBreakEven { new_sl: f64 },
    /// Trail the SL to a new (better) level.
    TrailStop { new_sl: f64 },
    /// Close a fraction of the position (partial take-profit).
    PartialClose { fraction: f64, reason: String },
    /// No action needed.
    NoAction,
}

/// Per-position trailing stop state tracker.
#[derive(Debug, Clone)]
pub struct TrailingStopState {
    /// Entry price of the position.
    pub entry_price: f64,
    /// Initial stop-loss level.
    pub initial_sl: f64,
    /// Current (dynamic) stop-loss level.
    pub current_sl: f64,
    /// Whether we've already moved SL to break-even.
    pub break_even_triggered: bool,
    /// Number of partial take-profit closures executed (0, 1, or 2).
    pub partial_takes: u8,
    /// Position side: true = long, false = short.
    pub is_long: bool,
    /// Original risk distance (|entry - initial_sl|).
    pub risk_distance: f64,
}

impl TrailingStopState {
    pub fn new(entry_price: f64, initial_sl: f64, is_long: bool) -> Self {
        let risk_distance = (entry_price - initial_sl).abs();
        Self {
            entry_price,
            initial_sl,
            current_sl: initial_sl,
            break_even_triggered: false,
            partial_takes: 0,
            is_long,
            risk_distance,
        }
    }

    /// Update the trailing stop based on current price and ATR.
    ///
    /// # Logic
    /// 1. If PnL > +1% and break-even not triggered → move SL to entry price
    /// 2. If PnL > +2% → trail SL at `current_price - (atr * 2.0)` for longs
    /// 3. If PnL reaches 1:1 R:R and `partial_takes == 0` → partial close 25%
    /// 4. If PnL reaches 2:1 R:R and `partial_takes == 1` → partial close 25%
    pub fn update_trailing_stop(
        &mut self,
        current_price: f64,
        atr: f64,
    ) -> TrailingStopUpdate {
        if self.entry_price <= 0.0 || current_price <= 0.0 {
            return TrailingStopUpdate::NoAction;
        }

        // Calculate unrealized PnL percentage
        let pnl_pct = if self.is_long {
            (current_price - self.entry_price) / self.entry_price
        } else {
            (self.entry_price - current_price) / self.entry_price
        };

        // Check partial take-profit levels FIRST (higher priority to lock in profits)
        // 2:1 R:R partial (second partial close)
        if self.partial_takes == 1 && self.risk_distance > 0.0 {
            let current_reward = if self.is_long {
                current_price - self.entry_price
            } else {
                self.entry_price - current_price
            };
            let rr_ratio = current_reward / self.risk_distance;
            if rr_ratio >= 2.0 {
                self.partial_takes = 2;
                return TrailingStopUpdate::PartialClose {
                    fraction: 0.25,
                    reason: format!("2:1 R:R reached ({:.1}:1)", rr_ratio),
                };
            }
        }

        // 1:1 R:R partial (first partial close)
        if self.partial_takes == 0 && self.risk_distance > 0.0 {
            let current_reward = if self.is_long {
                current_price - self.entry_price
            } else {
                self.entry_price - current_price
            };
            let rr_ratio = current_reward / self.risk_distance;
            if rr_ratio >= 1.0 {
                self.partial_takes = 1;
                return TrailingStopUpdate::PartialClose {
                    fraction: 0.25,
                    reason: format!("1:1 R:R reached ({:.1}:1)", rr_ratio),
                };
            }
        }

        // Trailing stop with ATR: only when PnL > 2%
        if pnl_pct > 0.02 && atr > 0.0 {
            let new_trail = if self.is_long {
                current_price - (atr * 2.0)
            } else {
                current_price + (atr * 2.0)
            };

            // Never move SL backwards (towards worse execution)
            let improved = if self.is_long {
                new_trail > self.current_sl
            } else {
                new_trail < self.current_sl
            };

            if improved {
                self.current_sl = new_trail;
                return TrailingStopUpdate::TrailStop { new_sl: new_trail };
            }
        }

        // Break-even move: once PnL > 1%
        if pnl_pct > 0.01 && !self.break_even_triggered {
            self.break_even_triggered = true;
            self.current_sl = self.entry_price;
            return TrailingStopUpdate::MoveToBreakEven { new_sl: self.entry_price };
        }

        TrailingStopUpdate::NoAction
    }
}

/// Extension to ExitEvaluator for trailing stop management.
impl ExitEvaluator {
    /// Get or create a trailing stop state for a position.
    /// Called when a position is opened to begin trailing stop tracking.
    pub fn init_trailing_stop(
        &mut self,
        symbol_id: u16,
        entry_price: f64,
        initial_sl: f64,
        _is_long: bool,
    ) {
        if let Some(_state) = self.positions.get_mut(&symbol_id) {
            // Attach trailing stop state metadata (we store via existing fields)
            info!(
                "[exit-eval] 📊 Trailing stop initialized for sym {}: entry={:.4}, SL={:.4}, risk={:.4}",
                symbol_id, entry_price, initial_sl, (entry_price - initial_sl).abs()
            );
            // The trailing stop logic is managed by TrailingStopState externally
        }
    }

    /// Get the current ATR value for a tracked position.
    pub fn get_position_atr(&self, symbol_id: u16) -> f64 {
        self.positions
            .get(&symbol_id)
            .map(|s| s.atr.get())
            .unwrap_or(0.0)
    }

    /// Get the entry price for a tracked position.
    pub fn get_entry_price(&self, symbol_id: u16) -> Option<f64> {
        self.positions.get(&symbol_id).map(|s| s.entry_price)
    }

    /// Check if a position is long.
    pub fn is_position_long(&self, symbol_id: u16) -> Option<bool> {
        self.positions.get(&symbol_id).map(|s| s.is_long)
    }

    /// Get position size.
    pub fn get_position_size(&self, symbol_id: u16) -> Option<i64> {
        self.positions.get(&symbol_id).map(|s| s.size)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════

#[inline]
fn now_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos() as u64
}

// ═══════════════════════════════════════════════════════════════════════════
// Unit Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hard_stop_loss_long() {
        let mut eval = ExitEvaluator::new();
        eval.track_position(1, true, 50000.0, 49000.0, 52000.0, 10, 0);

        // Price above SL — no exit
        let signals = eval.evaluate_all(1, 50500.0, 49500.0, 50000.0, 50000.0);
        assert!(signals.is_empty());

        // Price at SL — exit
        let signals = eval.evaluate_all(1, 49500.0, 48500.0, 49000.0, 49000.0);
        assert_eq!(signals.len(), 1);
        assert_eq!(signals[0].reason, ExitReason::HardStopLoss);
        assert_eq!(signals[0].exit_side, 1); // sell to close long
        assert_eq!(signals[0].urgency, 2);
    }

    #[test]
    fn test_take_profit_long() {
        let mut eval = ExitEvaluator::new();
        eval.track_position(1, true, 50000.0, 49000.0, 52000.0, 10, 0);

        // Price below TP
        let signals = eval.evaluate_all(1, 51500.0, 50500.0, 51000.0, 51000.0);
        assert!(signals.is_empty());

        // Price at TP
        let signals = eval.evaluate_all(1, 52500.0, 51500.0, 52000.0, 52000.0);
        assert_eq!(signals.len(), 1);
        assert_eq!(signals[0].reason, ExitReason::TakeProfit);
    }

    #[test]
    fn test_hard_stop_loss_short() {
        let mut eval = ExitEvaluator::new();
        eval.track_position(1, false, 50000.0, 51000.0, 48000.0, 10, 0);

        // Price below SL (short) — no exit
        let signals = eval.evaluate_all(1, 50500.0, 49500.0, 50000.0, 50000.0);
        assert!(signals.is_empty());

        // Price at SL (short) — exit
        let signals = eval.evaluate_all(1, 51500.0, 50500.0, 51000.0, 51000.0);
        assert_eq!(signals.len(), 1);
        assert_eq!(signals[0].exit_side, 0); // buy to close short
    }

    #[test]
    fn test_parabolic_sar() {
        let mut psar = ParabolicSarState::new(100.0, true);

        // Trending up — no cross
        assert!(!psar.update(102.0, 100.0));
        assert!(!psar.update(104.0, 101.0));
        assert!(!psar.update(106.0, 103.0));

        // Sharp reversal — SAR crossed
        let crossed = psar.update(103.0, 90.0);
        assert!(crossed);
    }

    #[test]
    fn test_atr_calculator() {
        let mut atr = AtrCalculator::new(3);

        atr.update(105.0, 95.0, 100.0);  // TR = 10
        atr.update(108.0, 98.0, 105.0);  // TR = 10
        atr.update(110.0, 100.0, 108.0); // TR = 10

        // After 3 bars with TR=10, ATR should be ~10
        let val = atr.get();
        assert!((val - 10.0).abs() < 0.5, "ATR should be ~10, got {}", val);
    }

    #[test]
    fn test_untrack_position() {
        let mut eval = ExitEvaluator::new();
        eval.track_position(1, true, 50000.0, 49000.0, 52000.0, 10, 0);
        assert!(eval.is_tracking(1));

        eval.untrack_position(1);
        assert!(!eval.is_tracking(1));
    }

    #[test]
    fn test_update_sl_tp() {
        let mut eval = ExitEvaluator::new();
        eval.track_position(1, true, 50000.0, 49000.0, 52000.0, 10, 0);

        // Move SL tighter
        eval.update_sl_tp(1, 49500.0, 53000.0);

        // Price at old SL but above new SL — no exit
        let signals = eval.evaluate_all(1, 49800.0, 49200.0, 49500.0, 49500.0);
        // Should now trigger at 49500
        assert_eq!(signals.len(), 1);
    }
}

