//! Event-Sourced Order State Machine — Institutional Grade.
//!
//! Implements a strict state machine that reconciles *intended* order state
//! against *actual* Gate.io exchange state.  Every order transitions through
//! well-defined states, and any state that lingers beyond a configurable
//! timeout triggers automatic cancellation and slot release.
//!
//! # Design Principles
//!
//! 1. **Never trust local state alone** — always reconcile with exchange.
//! 2. **Timeout-driven cleanup** — hanging orders are force-cancelled.
//! 3. **Event sourcing** — every transition is journaled for replay.
//! 4. **Gate.io exclusive** — no abstraction layers for other exchanges.

use std::collections::HashMap;
use std::time::{Duration, Instant};
use tracing::{info, warn};

use crate::execution_gateway::ExecutionGateway;

// ═══════════════════════════════════════════════════════════════════════════
// Order States
// ═══════════════════════════════════════════════════════════════════════════

/// Strict order lifecycle states — no implicit transitions allowed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderState {
    /// Order intent generated by strategy, not yet submitted.
    Pending,
    /// Order submitted to Gate.io REST/WS, awaiting ACK.
    Submitted,
    /// Gate.io acknowledged the order (has an exchange order ID).
    Acknowledged,
    /// Order partially filled.
    PartiallyFilled,
    /// Order fully filled — terminal state.
    Filled,
    /// Order rejected by Gate.io or pre-trade risk — terminal state.
    Rejected,
    /// Order cancelled (by us or by exchange) — terminal state.
    Cancelled,
    /// Order timed out waiting for fill — will be force-cancelled.
    TimedOut,
}

impl OrderState {
    /// Returns true if this is a terminal state (no further transitions).
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            OrderState::Filled | OrderState::Rejected | OrderState::Cancelled
        )
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Order Event (Event Sourcing)
// ═══════════════════════════════════════════════════════════════════════════

/// Events that drive state transitions.
#[derive(Debug, Clone)]
pub enum OrderEvent {
    /// Strategy emitted an order intent.
    Created { client_oid: String, symbol: String },
    /// Order submitted to Gate.io.
    Submitted { exchange_oid: Option<String> },
    /// Gate.io acknowledged the order.
    Acknowledged { exchange_oid: String },
    /// Partial fill received.
    PartialFill { filled_qty: i64, remaining_qty: i64 },
    /// Full fill received.
    FullFill { avg_price: f64, total_qty: i64 },
    /// Order rejected by exchange or pre-trade risk.
    Rejected { reason: String },
    /// Order cancelled (timeout, manual, or exchange-initiated).
    Cancelled { reason: String },
    /// Reconciliation detected order no longer exists on exchange.
    Reconciled { exchange_state: String },
}

// ═══════════════════════════════════════════════════════════════════════════
// Tracked Order
// ═══════════════════════════════════════════════════════════════════════════

/// A single order being tracked through its lifecycle.
#[derive(Debug, Clone)]
pub struct TrackedOrder {
    pub client_oid: String,
    pub exchange_oid: Option<String>,
    pub symbol: String,
    pub state: OrderState,
    pub created_at: Instant,
    pub last_transition: Instant,
    pub events: Vec<OrderEvent>,
}

impl TrackedOrder {
    pub fn new(client_oid: String, symbol: String) -> Self {
        let now = Instant::now();
        let event = OrderEvent::Created {
            client_oid: client_oid.clone(),
            symbol: symbol.clone(),
        };
        Self {
            client_oid,
            exchange_oid: None,
            symbol,
            state: OrderState::Pending,
            created_at: now,
            last_transition: now,
            events: vec![event],
        }
    }

    /// Apply an event, transitioning the state machine.
    /// Returns the new state, or an error if the transition is invalid.
    pub fn apply_event(&mut self, event: OrderEvent) -> Result<OrderState, String> {
        let new_state = match (&self.state, &event) {
            (OrderState::Pending, OrderEvent::Submitted { exchange_oid }) => {
                self.exchange_oid = exchange_oid.clone();
                OrderState::Submitted
            }
            (OrderState::Pending, OrderEvent::Rejected { .. }) => OrderState::Rejected,

            (OrderState::Submitted, OrderEvent::Acknowledged { exchange_oid }) => {
                self.exchange_oid = Some(exchange_oid.clone());
                OrderState::Acknowledged
            }
            (OrderState::Submitted, OrderEvent::Rejected { .. }) => OrderState::Rejected,
            (OrderState::Submitted, OrderEvent::FullFill { .. }) => OrderState::Filled,
            (OrderState::Submitted, OrderEvent::Cancelled { .. }) => OrderState::Cancelled,

            (OrderState::Acknowledged, OrderEvent::PartialFill { .. }) => {
                OrderState::PartiallyFilled
            }
            (OrderState::Acknowledged, OrderEvent::FullFill { .. }) => OrderState::Filled,
            (OrderState::Acknowledged, OrderEvent::Cancelled { .. }) => OrderState::Cancelled,

            (OrderState::PartiallyFilled, OrderEvent::PartialFill { .. }) => {
                OrderState::PartiallyFilled
            }
            (OrderState::PartiallyFilled, OrderEvent::FullFill { .. }) => OrderState::Filled,
            (OrderState::PartiallyFilled, OrderEvent::Cancelled { .. }) => {
                OrderState::Cancelled
            }

            // Reconciliation can force any non-terminal state to terminal
            (s, OrderEvent::Reconciled { exchange_state }) if !s.is_terminal() => {
                match exchange_state.as_str() {
                    "filled" => OrderState::Filled,
                    "cancelled" => OrderState::Cancelled,
                    _ => OrderState::Cancelled, // Unknown exchange state → cancel
                }
            }

            (state, event) => {
                return Err(format!(
                    "Invalid transition: {:?} + {:?} for order {}",
                    state, event, self.client_oid
                ));
            }
        };

        self.state = new_state;
        self.last_transition = Instant::now();
        self.events.push(event);
        Ok(new_state)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Order State Machine Manager
// ═══════════════════════════════════════════════════════════════════════════

/// Manages the lifecycle of all active orders with automatic timeout
/// detection and exchange reconciliation.
pub struct OrderStateMachine {
    /// Active (non-terminal) orders indexed by client_oid.
    orders: HashMap<String, TrackedOrder>,
    /// Maximum time an order can stay in Submitted/Acknowledged before
    /// being force-cancelled.
    order_timeout: Duration,
    /// Maximum time a partially-filled order waits for completion.
    partial_fill_timeout: Duration,
    /// Total orders processed (for metrics).
    total_processed: u64,
    /// Total orders timed out.
    total_timeouts: u64,
}

impl OrderStateMachine {
    pub fn new() -> Self {
        Self {
            orders: HashMap::new(),
            order_timeout: Duration::from_secs(30),
            partial_fill_timeout: Duration::from_secs(60),
            total_processed: 0,
            total_timeouts: 0,
        }
    }

    /// Register a new order in the state machine.
    pub fn track_order(&mut self, client_oid: String, symbol: String) {
        let order = TrackedOrder::new(client_oid.clone(), symbol);
        self.orders.insert(client_oid, order);
        self.total_processed += 1;
    }

    /// Apply an event to a tracked order.
    pub fn apply_event(
        &mut self,
        client_oid: &str,
        event: OrderEvent,
    ) -> Result<OrderState, String> {
        let order = self
            .orders
            .get_mut(client_oid)
            .ok_or_else(|| format!("Order {} not found in state machine", client_oid))?;

        let new_state = order.apply_event(event)?;

        // Clean up terminal orders (keep last 100 for debugging)
        if new_state.is_terminal() {
            // Move to completed — we don't need to track it anymore
            info!(
                "[state_machine] Order {} reached terminal state {:?}",
                client_oid, new_state
            );
        }

        Ok(new_state)
    }

    /// Check for timed-out orders and return their client OIDs + symbols
    /// for force cancellation.
    pub fn check_timeouts(&mut self) -> Vec<(String, String, Option<String>)> {
        let now = Instant::now();
        let mut timed_out = Vec::new();

        for (oid, order) in &self.orders {
            let timeout = match order.state {
                OrderState::Submitted | OrderState::Acknowledged => self.order_timeout,
                OrderState::PartiallyFilled => self.partial_fill_timeout,
                _ => continue,
            };

            if now.duration_since(order.last_transition) > timeout {
                timed_out.push((
                    oid.clone(),
                    order.symbol.clone(),
                    order.exchange_oid.clone(),
                ));
            }
        }

        self.total_timeouts += timed_out.len() as u64;
        timed_out
    }

    /// Reconcile local state against the exchange.
    ///
    /// For each non-terminal order, query Gate.io for the actual order status.
    /// If the exchange says the order is filled/cancelled but we think it's
    /// still active, force a state transition.
    pub async fn reconcile(
        &mut self,
        gateway: &dyn ExecutionGateway,
    ) -> Vec<String> {
        let mut reconciled = Vec::new();

        let active_orders: Vec<(String, String, Option<String>)> = self
            .orders
            .iter()
            .filter(|(_, o)| !o.state.is_terminal())
            .map(|(oid, o)| (oid.clone(), o.symbol.clone(), o.exchange_oid.clone()))
            .collect();

        for (client_oid, symbol, exchange_oid) in active_orders {
            if let Some(ref ex_oid) = exchange_oid {
                match gateway.get_order_status(ex_oid, &symbol).await {
                    Ok(Some(result)) => {
                        // Order still exists on exchange — check if filled
                        if result.status == "finished" || result.status == "filled" {
                            let _ = self.apply_event(
                                &client_oid,
                                OrderEvent::Reconciled {
                                    exchange_state: "filled".to_string(),
                                },
                            );
                            reconciled.push(client_oid.clone());
                        }
                    }
                    Ok(None) => {
                        // Order doesn't exist on exchange → it was filled or cancelled
                        warn!(
                            "[state_machine] Order {} ({}) not found on exchange — reconciling as cancelled",
                            client_oid, ex_oid
                        );
                        let _ = self.apply_event(
                            &client_oid,
                            OrderEvent::Reconciled {
                                exchange_state: "cancelled".to_string(),
                            },
                        );
                        reconciled.push(client_oid.clone());
                    }
                    Err(e) => {
                        warn!(
                            "[state_machine] Reconciliation query failed for {}: {}",
                            client_oid, e
                        );
                    }
                }
            }
        }

        // Garbage collect terminal orders older than 5 minutes
        let gc_threshold = Instant::now() - Duration::from_secs(300);
        self.orders.retain(|_, o| {
            !o.state.is_terminal() || o.last_transition > gc_threshold
        });

        reconciled
    }

    /// Return the count of non-terminal orders.
    pub fn active_count(&self) -> usize {
        self.orders
            .values()
            .filter(|o| !o.state.is_terminal())
            .count()
    }

    /// Return metrics for the dashboard.
    pub fn metrics(&self) -> (u64, u64, usize) {
        (self.total_processed, self.total_timeouts, self.active_count())
    }
}

impl Default for OrderStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_happy_path() {
        let mut sm = OrderStateMachine::new();
        sm.track_order("test-1".into(), "BTC_USDT".into());

        let s = sm
            .apply_event(
                "test-1",
                OrderEvent::Submitted {
                    exchange_oid: Some("ex-123".into()),
                },
            )
            .unwrap();
        assert_eq!(s, OrderState::Submitted);

        let s = sm
            .apply_event(
                "test-1",
                OrderEvent::Acknowledged {
                    exchange_oid: "ex-123".into(),
                },
            )
            .unwrap();
        assert_eq!(s, OrderState::Acknowledged);

        let s = sm
            .apply_event(
                "test-1",
                OrderEvent::FullFill {
                    avg_price: 50000.0,
                    total_qty: 10,
                },
            )
            .unwrap();
        assert_eq!(s, OrderState::Filled);
    }

    #[test]
    fn test_rejection() {
        let mut sm = OrderStateMachine::new();
        sm.track_order("test-2".into(), "ETH_USDT".into());

        let s = sm
            .apply_event(
                "test-2",
                OrderEvent::Rejected {
                    reason: "insufficient margin".into(),
                },
            )
            .unwrap();
        assert_eq!(s, OrderState::Rejected);
        assert!(sm.orders["test-2"].state.is_terminal());
    }

    #[test]
    fn test_timeout_detection() {
        let mut sm = OrderStateMachine::new();
        sm.order_timeout = Duration::from_millis(1); // Instant timeout for test
        sm.track_order("test-3".into(), "SOL_USDT".into());

        let _ = sm.apply_event(
            "test-3",
            OrderEvent::Submitted {
                exchange_oid: Some("ex-456".into()),
            },
        );

        std::thread::sleep(Duration::from_millis(5));
        let timeouts = sm.check_timeouts();
        assert_eq!(timeouts.len(), 1);
        assert_eq!(timeouts[0].0, "test-3");
    }

    #[test]
    fn test_reconciliation_force_cancel() {
        let mut sm = OrderStateMachine::new();
        sm.track_order("test-4".into(), "BNB_USDT".into());

        let _ = sm.apply_event(
            "test-4",
            OrderEvent::Submitted {
                exchange_oid: Some("ex-789".into()),
            },
        );

        // Simulate reconciliation finding order cancelled on exchange
        let s = sm
            .apply_event(
                "test-4",
                OrderEvent::Reconciled {
                    exchange_state: "cancelled".into(),
                },
            )
            .unwrap();
        assert_eq!(s, OrderState::Cancelled);
    }
}
